/*
 * Using LCDs - Simple Up Counter
 * Target: NUCLEO-F446RE / STM32F446RET6
 * Framework: STM32CubeF4 HAL
 *
 * Independently rewritten for the F446RE board.
 * This is not a copy of the book's program listing.
 */
#include "stm32f4xx_hal.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>


static void SystemClock_Config(void)
{
    RCC_OscInitTypeDef osc = {0};
    RCC_ClkInitTypeDef clk = {0};

    __HAL_RCC_PWR_CLK_ENABLE();

    osc.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    osc.HSIState = RCC_HSI_ON;
    osc.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    osc.PLL.PLLState = RCC_PLL_NONE;
    if (HAL_RCC_OscConfig(&osc) != HAL_OK) {
        while (1) {}
    }

    clk.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK |
                    RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
    clk.AHBCLKDivider = RCC_SYSCLK_DIV1;
    clk.APB1CLKDivider = RCC_HCLK_DIV1;
    clk.APB2CLKDivider = RCC_HCLK_DIV1;
    if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_0) != HAL_OK) {
        while (1) {}
    }
}

/*
 * Connect a 16x2 HD44780 LCD in 4-bit mode.
 * Suggested pins: PB0=RS, PB1=EN, PB2=D4, PB12=D5, PB13=D6, PB14=D7.
 *
 * Add your small lcd.c/lcd.h driver to the CubeIDE project. The application
 * below deliberately keeps the LCD driver separate from main.c.
 */
#include "lcd.h"
int main(void)
{
    HAL_Init(); SystemClock_Config();
    MX_GPIO_Init();   /* generated by CubeMX for the pins above */
    lcd_init();

    uint32_t count=0; char s[17];
    while (1) {
        snprintf(s,sizeof(s),"Count: %lu",(unsigned long)count++);
        lcd_clear(); lcd_puts(s); HAL_Delay(1000);
    }
}
